version: '3.9'
services:
  carcalculator_db_dev:
    image: postgres:14-alpine
    container_name: carcalculator_db_dev
    restart: always
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: carcalculator

volumes:
  pgdata:
    name: carcalculator-dev-db
